# -*- coding: utf-8 -*-
"""banking_case.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M69h4GteOx6apkJ6tJIl7fQLQkh8LoFW
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("Banking.csv")

df.head()

df.shape

df.info()

df.describe()

df.isnull().sum()

bins =[0,100000,300000,float('inf')]
labels = ['Low', 'Medium', 'High']
df['Income Band'] = pd.cut(df['Estimated Income'], bins=bins, labels=labels)

df['Income Band']

df['Income Band'].value_counts()

df['Income Band'].value_counts().plot(kind = 'bar')

df.columns

# Examine the distribution of unique categoreis in categorical columns

categorical_cols = df[["BRId","GenderId","IAId","Amount of Credit Cards","Nationality","Occupation","Fee Structure","Loyalty Classification","Properties Owned","Risk Weighting","Income Band"]].columns
for col in categorical_cols:
    print(f"Unique values in {col}:")
    display(df[col].value_counts())
    print("\n")

"""# **Univariate Analysis**"""

for i, predictor in enumerate(df[["BRId","GenderId","IAId","Amount of Credit Cards","Nationality","Occupation","Fee Structure","Loyalty Classification","Properties Owned","Risk Weighting","Income Band"]].columns):
  plt.figure(i)
  sns.countplot(data=df, x=predictor)

"""# **Bivariate** **Analysis**




"""

for i, predictor in enumerate(df[["BRId","GenderId","IAId","Amount of Credit Cards","Nationality","Occupation","Fee Structure","Loyalty Classification","Properties Owned","Risk Weighting","Income Band"]].columns):
  plt.figure(i)
  sns.countplot(data=df, x=predictor, hue='Nationality')

"""# **Numericsal** **Analysis**  """

df.columns

numerical_col =['Estimated Income','Superannuation Savings','Credit Card Balance','Bank Loans','Bank Deposits','Checking Accounts', 'Saving Accounts','Foreign Currency Account','Business Lending' ]

# Univariate analysis and visualization
plt.figure(figsize=(15,8))
for i,col in enumerate(numerical_col):
  plt.subplot(4,3,i+1)
  sns.histplot(df[col],kde=True)
  plt.title(f'Distribution of {col}')
  plt.xlabel(col)
  plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

"""# **Heatmaps**"""

numerical_col =['Estimated Income','Superannuation Savings','Credit Card Balance','Bank Loans','Bank Deposits','Checking Accounts', 'Saving Accounts','Foreign Currency Account','Business Lending' ]

correlation_matrix = df[numerical_col].corr()

plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm',fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()

"""# Insights of EDA

1. The strongest positive correlation occur among "Bank Deposits"  with "Cheking Account", "Saving Accounts","Foreign Currency Account"  indicatoing that customers who maintain in one account type often hold substantial amount/funds across account as well
"""

